# frontend/nginx.conf


server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # SPA Fallback routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: Reverse proxy to backend for local API calls
    location /api/ {
        # NO trailing slash at the end of 5000 (PORT number)
        proxy_pass http://backend:5000;   # <-- Change this based on backend server PORT number

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Required for Socket.IO and WebRTC signaling
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

    }

    # Optional: If Socket.IO uses its default path instead of /api/
    location /socket.io/ {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}