// frontend/src/schemas/user.schema.ts
import { passwordBase } from "@/schemas/auth.schema";
import { z } from "zod";


/* ---------- Base Fields ---------- */
export const nameBase = z
  .string()
  .trim()
  .min(1, "Full name is required")
  .min(3, "Full name must be at least 3 characters")
  .max(20, "Full name cannot exceed 20 characters")
  .regex(
    /^[A-Za-z]+(?:\s[A-Za-z]+)*$/,
    "Full name can contain only letters and spaces"
  );



export const emailBase = z
  .string()
  .min(1, { message: "Email is required" })
  .trim()
  .toLowerCase()
  .email({ message: "Please enter a valid email address" });





export const mobileBase = z
  .string()
  .trim()
  .optional()
  .superRefine((val, ctx) => {
    if (!val) return;

    if (!/^\d+$/.test(val)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Mobile number must contain digits only",
      });
      return;
    }

    if (val.length !== 10) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Mobile number must be exactly 10 digits",
      });
      return;
    }

    if (!/^[6-9]/.test(val)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Please enter a valid Indian mobile number (start with 6, 7, 8, or 9)",
      });
    }
  });








export const roleBase = z.enum(["user", "host", "admin"], {
  error: "Invalid user role selected",
});



export const statusBase = z.enum(["active", "blocked", "pending"], {
  error: "Invalid user status selected",
});


export const MAX_IMAGE_SIZE = 2 * 1024 * 1024; // 2MB
export const ACCEPTED_IMAGE_TYPES = ['image/jpg', "image/jpeg", "image/png", 'image/gif', "image/webp"];




  export const profilePicBase = z
  .instanceof(File, { message: "Invalid file" })
  .refine((file) => file.size <= MAX_IMAGE_SIZE, {
    message: `Profile image must be less than ${MAX_IMAGE_SIZE / (1024 * 1024)}MB`,
  })
  .refine((file) => ACCEPTED_IMAGE_TYPES.includes(file.type), {
    message: "Only JPG, JPEG, PNG, GIF and WEBP images are allowed",
  })
  .optional();







/* ---------- User Form Schema ---------- */
export const userFormSchema = z.object({
  name: nameBase,
  email: emailBase,
  mobile: mobileBase,
  role: roleBase,
  status: statusBase,
//   profilePic: profilePicBase,  // profile pic is not validating with zod
    //   password: passwordBase,  // auto password generated by system or default password
    // confirmPassword: z.string(),
    // agreeTerms: agreeTermsBase,
  })
//   .refine((data) => data.password === data.confirmPassword, {
//     path: ["confirmPassword"],
//     message: "Passwords do not match.",
//   })




/* ---------- User Basic Info Updating Schema ---------- */
export const updateBasicInfoSchema = z.object({
  name: nameBase,
  mobile: mobileBase,
});




/* ---------- Profile Pic Updating Schema ---------- */
export const profilePicUploadSchema = z.object({
  profileImage: profilePicBase,
});



/* ---------- Change Password Schema ---------- */
export const changePasswordSchema = z
  .object({
    currentPassword: z.string().min(1, "Current password is required"),
    newPassword: passwordBase,
    confirmPassword: z.string().min(1, "Please confirm your new password"),
  })
  .refine((data) => data.newPassword === data.confirmPassword, {
    path: ["confirmPassword"],
    message: "Passwords do not match",
  })
  .refine((data) => data.currentPassword !== data.newPassword, {
    path: ["newPassword"],
    message: "New password must be different from your current password",
  });
 
export type ChangePasswordData = z.infer<typeof changePasswordSchema>;