// frontend/src/schemas/user.schema.ts
import { z } from "zod";


/* ---------- Base Fields ---------- */
export const nameBase = z
  .string()
  .trim()
  .min(1, "Full name is required")
  .min(3, "Full name must be at least 3 characters long")
  .max(20, "Full name cannot exceed 20 characters")
  .regex(
    /^[A-Za-z]+(?:\s[A-Za-z]+)*$/,
    "Full name can contain only letters and spaces"
  );



export const emailBase = z
  .string()
  .trim()
  .email("Please enter a valid email address");



export const mobileBase = z
   .string()
   .transform((val) => val.trim())
   .refine((val) => val === "" || /^\d+$/.test(val), {
      message: "Mobile number must contain only digits (0-9)",
   })
   .refine((val) => val === "" || val.length === 10, {
      message: "Mobile number must be exactly 10 digits",
   })
   .optional();




export const roleBase = z.enum(["user", "host", "admin"], {
  error: "Invalid user role selected",
});



export const statusBase = z.enum(["active", "blocked", "pending"], {
  error: "Invalid user status selected",
});


const MAX_FILE_SIZE = 2 * 1024 * 1024; // 2MB
const ACCEPTED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"];



export const profilePicBase = z
  .custom<File>((val) => val instanceof File, {
    message: "Invalid file",
  })
  .refine((file) => file.size <= MAX_FILE_SIZE, {
    message: "Profile image must be less than 2MB",
  })
  .refine((file) => ACCEPTED_IMAGE_TYPES.includes(file.type), {
    message: "Only JPG, PNG, and WEBP images are allowed",
  })
  .optional();






/* ---------- User Form Schema ---------- */
export const userFormSchema = z.object({
  name: nameBase,
  email: emailBase,
  mobile: mobileBase,
  role: roleBase,
  status: statusBase,
//   profilePic: profilePicBase,  // profile pic is not validating with zod
    //   password: passwordBase,  // auto password generated by system or default password
    // confirmPassword: z.string(),
    // agreeTerms: agreeTermsBase,
  })
//   .refine((data) => data.password === data.confirmPassword, {
//     path: ["confirmPassword"],
//     message: "Passwords do not match.",
//   })
