// shared/schemas/user.schema.ts (for create user by admin, user profile & update)
import { z } from "zod";


export const nameBase = z
  .string()
  .min(3, "Full name is required")
  .max(20, "Full name cannot exceed 20 characters");


export const emailBase = z
  .string()
  .email("Invalid email address");


  export const agreeTermsBase = z.boolean().refine((val) => val === true, {
    message: "You must agree to the Terms and Conditions.",
  });





// User Schema
export const userFormSchema = z
  .object({
    name: nameBase,
    email: emailBase,
    mobile: z.string().min(10).max(15).optional(),
    role: z.enum(['user', 'host', 'admin']),
    status: z.enum(['active', 'blocked']),
    profilePic: z.string().url().optional(),
    // password: passwordBase,  // auto password generated by system or default password
    // confirmPassword: z.string(),
    // agreeTerms: agreeTermsBase,
  })
//   .refine((data) => data.password === data.confirmPassword, {
//     path: ["confirmPassword"],
//     message: "Passwords do not match.",
//   })


    